[package]
name = "vcm"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab_tree="0.3.2"
[target.'cfg(windows)'.dependencies]
native-windows-gui="1.0.13"
native-windows-derive="1.0.5"
